services:
  phpfpm:
    volumes:
      - ../../shared/.env.local:/app/.env.local
      - ../../shared/public/upload:/app/public/upload

  nginx:
    volumes:
      - ../../shared/public/upload:/app/public/upload:r
