when:
  event: cron
  cron: "Cache-clear"

skip_clone: true

steps:
  - name: Run cache clear
    image: itkdev/ansible-plugin:latest
    pull: true
    settings:
      PRIVATE_KEY:
        from_secret: ssh-key
      CERT:
        from_secret: ssh-cert
      HOST:
        from_secret: host
      PATH:
        from_secret: path
      USER:
        from_secret: user
      ACTIONS:
        - itkdev-docker-compose-server exec phpfpm bin/console cache:clear
