when:
  - event: push
    branch: develop

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"

  - name: Ansible test
    image: itkdev/ansible-plugin:latest
    environment:
      PLUGIN_PRIVATE_KEY:
        from_secret: ssh-key
      PLUGIN_CERT:
        from_secret: ssh-cert
      PLUGIN_HOST: 'deploy-test.itkdev.dk'
      PLUGIN_USER: 'deploy'
