when:
  - event: push
    branch: develop

skip_clone: true

steps:
  - name: Site 2 ansible test
    image: itkdev/ansible-plugin:latest
    pull: true
    settings:
      id:
        from_secret: id
      secret:
        from_secret: secret
      host:
        from_secret: host
      path:
        from_secret: path
      user:
        from_secret: user
      actions:
        - uptime
