when:
  - event: push
    branch: develop

skip_clone: true

steps:
  - name: Site 2 ansible test
    image: itkdev/ansible-plugin:latest
    pull: true
    settings:
      PRIVATE_KEY:
        from_secret: ssh-key
      CERT:
        from_secret: ssh-cert
      HOST:
        from_secret: host
      USER:
        from_secret: user
      ACTIONS:
        - uptime
