when:
  - event: push
    branch: develop

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"

  - name: Ansible playbook
    image: itkdev/ansible-plugin:latest
    pull: true
    settings:
      PRIVATE_KEY:
        from_secret: ssh-key
      CERT:
        from_secret: ssh-cert
      HOST:
        from_secret: host
      USER:
        from_secret: user
      PLAYBOOK: 'uptime'

  - name: Ansible
    image: itkdev/ansible-plugin:latest
    pull: true
    settings:
      PRIVATE_KEY:
        from_secret: ssh-key
      CERT:
        from_secret: ssh-cert
      HOST:
        from_secret: host
      USER:
        from_secret: user
      ACTIONS:
        - uptime
        - id
